### ISSUE TITLE
Vcon core package cannot output anything to stdout

### ISSUE THREAD

**Issue by dgpetrie** [vcon-dev/vcon#7]
print lines in the Vcon package were changed from output to stderr to stdout.  This breaks the CLI which outputs JSON or other file formats to std out (e.g. wav files).  When stuff is printed to stdout it creats invalid JSON or wav file output in the CLI.  If it is undesirable to have stderr output due to data dog or other log monitors, then the stderr out should be converted to use Python logging.

e.g. https://github.com/vcon-dev/vcon/commit/0260ff505333ecc5153fcfd702f0777fb0551339

**Comment by howethomas** [comment]
Where are we at with this?  Do you know if we've addressed it?

**Comment by dgpetrie** [comment]
This is fixed in my fix-stdout-originator-unittests branch
    On Saturday, April 8, 2023, 10:16:27 AM UTC, Thomas Howe ***@***.***> wrote:  
 
 


Where are we at with this? Do you know if we've addressed it?

**Comment by dgpetrie** [comment]
branch fix-stdout-originator-unittests merged to server-rehab, merged to main.
